/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package alienClicker2;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import javax.swing.JLabel;
import javax.swing.SwingConstants;


/**
 *
 * @author fedie2562
 */
public class alienClicker2 extends javax.swing.JFrame {
    
    DroneThread droneThread = new DroneThread();
    int prestigeCost = 1000000;
    int prestigeCount = 0;
    int credits = 0;
    int gain = 1;
    int suits = 0;
    int blasters = 0;
    int drones = 0;
    int nukes = 0;
    int fuel = 0;
    
    /**
     * Creates new form alienClicker2
     */
    public alienClicker2() {
        initComponents();
        droneThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPlace = new javax.swing.JPanel();
        prestigeCountLabel = new javax.swing.JLabel();
        shopButton = new javax.swing.JButton();
        prestige = new javax.swing.JButton();
        prestigeMessage = new javax.swing.JLabel();
        clickerScreen = new javax.swing.JButton();
        upgradeCounters = new javax.swing.JPanel();
        suitCount = new javax.swing.JLabel();
        blasterCount = new javax.swing.JLabel();
        nukeCount = new javax.swing.JLabel();
        fuelCount = new javax.swing.JLabel();
        droneCount = new javax.swing.JLabel();
        shopPanel2 = new javax.swing.JPanel();
        droneCostLabel = new javax.swing.JLabel();
        droneUpgrade = new javax.swing.JButton();
        bombCostLabel = new javax.swing.JLabel();
        bombUpgrade = new javax.swing.JButton();
        shopPanel = new javax.swing.JPanel();
        suitCostLabel = new javax.swing.JLabel();
        suitUpgrade = new javax.swing.JButton();
        blasterCostLabel = new javax.swing.JLabel();
        blasterUpgrade = new javax.swing.JButton();
        fuelCostLabel = new javax.swing.JLabel();
        fuelUpgrade = new javax.swing.JButton();
        creditCount = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        clicker = new javax.swing.JButton();
        alien_pic = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 600));
        setMinimumSize(new java.awt.Dimension(550, 600));
        setPreferredSize(new java.awt.Dimension(550, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        labelPlace.setOpaque(false);
        labelPlace.setLayout(new javax.swing.BoxLayout(labelPlace, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(labelPlace);
        labelPlace.setBounds(350, 240, 80, 20);

        prestigeCountLabel.setVisible(false);
        prestigeCountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prestigeCountLabel.setForeground(new java.awt.Color(0, 255, 0));
        prestigeCountLabel.setText("Prestige Count = ");
        getContentPane().add(prestigeCountLabel);
        prestigeCountLabel.setBounds(210, 10, 140, 30);

        shopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alienClicker2/Mothership s.png"))); // NOI18N
        shopButton.setBorderPainted(false);
        shopButton.setContentAreaFilled(false);
        shopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shopButton);
        shopButton.setBounds(390, 20, 150, 100);

        prestige.setVisible(false);
        prestige.setBackground(new java.awt.Color(255, 51, 51));
        prestige.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prestige.setForeground(new java.awt.Color(0, 255, 0));
        prestige.setText("PAY");
        prestige.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prestige.setContentAreaFilled(false);
        prestige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestigeActionPerformed(evt);
            }
        });
        getContentPane().add(prestige);
        prestige.setBounds(400, 50, 60, 30);

        prestigeMessage.setVisible(false);
        prestigeMessage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prestigeMessage.setForeground(new java.awt.Color(0, 255, 0));
        prestigeMessage.setText("Pay 1,000,000 credits and move to the next star system.");
        getContentPane().add(prestigeMessage);
        prestigeMessage.setBounds(120, 20, 440, 40);

        clickerScreen.setVisible(false);
        clickerScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alienClicker2/Alien.png"))); // NOI18N
        clickerScreen.setBorderPainted(false);
        clickerScreen.setContentAreaFilled(false);
        clickerScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickerScreenActionPerformed(evt);
            }
        });
        getContentPane().add(clickerScreen);
        clickerScreen.setBounds(280, 250, 330, 350);

        upgradeCounters.setOpaque(false);

        suitCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        suitCount.setForeground(new java.awt.Color(0, 255, 0));
        suitCount.setText("Suits: ");

        blasterCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        blasterCount.setForeground(new java.awt.Color(0, 255, 0));
        blasterCount.setText("Blasters: ");

        nukeCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nukeCount.setForeground(new java.awt.Color(0, 255, 0));
        nukeCount.setText("Nukes:");

        fuelCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fuelCount.setForeground(new java.awt.Color(0, 255, 0));
        fuelCount.setText("Fuel: ");

        droneCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        droneCount.setForeground(new java.awt.Color(0, 255, 0));
        droneCount.setText("Drones: ");

        javax.swing.GroupLayout upgradeCountersLayout = new javax.swing.GroupLayout(upgradeCounters);
        upgradeCounters.setLayout(upgradeCountersLayout);
        upgradeCountersLayout.setHorizontalGroup(
            upgradeCountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upgradeCountersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upgradeCountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suitCount)
                    .addComponent(blasterCount)
                    .addComponent(nukeCount)
                    .addComponent(fuelCount)
                    .addComponent(droneCount))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        upgradeCountersLayout.setVerticalGroup(
            upgradeCountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upgradeCountersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suitCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blasterCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nukeCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fuelCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(droneCount)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(upgradeCounters);
        upgradeCounters.setBounds(10, 80, 90, 150);

        shopPanel2.setOpaque(false);
        shopPanel2.setVisible(false);

        droneCostLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        droneCostLabel.setForeground(new java.awt.Color(0, 255, 0));
        droneCostLabel.setText("COST: 1000");

        droneUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alienClicker2/drone.png"))); // NOI18N
        droneUpgrade.setBorderPainted(false);
        droneUpgrade.setContentAreaFilled(false);
        droneUpgrade.setPreferredSize(new java.awt.Dimension(105, 60));
        droneUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                droneUpgradeActionPerformed(evt);
            }
        });

        bombCostLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bombCostLabel.setForeground(new java.awt.Color(0, 255, 0));
        bombCostLabel.setText("COST: 5000");

        bombUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alienClicker2/nuke.png"))); // NOI18N
        bombUpgrade.setBorderPainted(false);
        bombUpgrade.setContentAreaFilled(false);
        bombUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bombUpgradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shopPanel2Layout = new javax.swing.GroupLayout(shopPanel2);
        shopPanel2.setLayout(shopPanel2Layout);
        shopPanel2Layout.setHorizontalGroup(
            shopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shopPanel2Layout.createSequentialGroup()
                .addGroup(shopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(shopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(shopPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(droneUpgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(shopPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(bombUpgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(shopPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(droneCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(shopPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bombCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        shopPanel2Layout.setVerticalGroup(
            shopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shopPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(droneCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(droneUpgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bombCostLabel)
                .addGap(5, 5, 5)
                .addComponent(bombUpgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(shopPanel2);
        shopPanel2.setBounds(120, 350, 142, 176);

        shopPanel.setMaximumSize(new java.awt.Dimension(150, 420));
        shopPanel.setOpaque(false);
        shopPanel.setVisible(false);
        shopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suitCostLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        suitCostLabel.setForeground(new java.awt.Color(0, 255, 0));
        suitCostLabel.setText("COST: 500");
        shopPanel.add(suitCostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 103, -1));

        suitUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alienClicker2/alienSuit.png"))); // NOI18N
        suitUpgrade.setBorder(null);
        suitUpgrade.setBorderPainted(false);
        suitUpgrade.setContentAreaFilled(false);
        suitUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suitUpgradeActionPerformed(evt);
            }
        });
        shopPanel.add(suitUpgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 103, 143));

        blasterCostLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        blasterCostLabel.setForeground(new java.awt.Color(0, 255, 0));
        blasterCostLabel.setText("COST: 100");
        shopPanel.add(blasterCostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, 99, -1));

        blasterUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alienClicker2/alienBlaster.png"))); // NOI18N
        blasterUpgrade.setBorderPainted(false);
        blasterUpgrade.setContentAreaFilled(false);
        blasterUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blasterUpgradeActionPerformed(evt);
            }
        });
        shopPanel.add(blasterUpgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 199, 99, 76));

        fuelCostLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fuelCostLabel.setForeground(new java.awt.Color(0, 255, 0));
        fuelCostLabel.setText("COST: 50");
        shopPanel.add(fuelCostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 293, 99, -1));

        fuelUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alienClicker2/alienFuel.png"))); // NOI18N
        fuelUpgrade.setBorderPainted(false);
        fuelUpgrade.setContentAreaFilled(false);
        fuelUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelUpgradeActionPerformed(evt);
            }
        });
        shopPanel.add(fuelUpgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 314, 109, 106));

        getContentPane().add(shopPanel);
        shopPanel.setBounds(0, 150, 140, 430);

        creditCount.setBackground(new java.awt.Color(0, 255, 0));
        creditCount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        creditCount.setForeground(new java.awt.Color(0, 255, 0));
        creditCount.setText("Credits: ");
        getContentPane().add(creditCount);
        creditCount.setBounds(10, 40, 170, 40);

        title.setBackground(new java.awt.Color(0, 0, 0));
        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 255, 0));
        title.setText("Alien Clicker 2.0");
        getContentPane().add(title);
        title.setBounds(0, 0, 210, 30);

        clicker.setBorderPainted(false);
        clicker.setContentAreaFilled(false);
        clicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickerActionPerformed(evt);
            }
        });
        getContentPane().add(clicker);
        clicker.setBounds(310, 250, 190, 240);

        alien_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alienClicker2/Alien.png"))); // NOI18N
        alien_pic.setText("jLabel2");
        getContentPane().add(alien_pic);
        alien_pic.setBounds(210, 240, 330, 360);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alienClicker2/727311main_heart_full_full.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(550, 600));
        background.setMinimumSize(new java.awt.Dimension(550, 600));
        background.setPreferredSize(new java.awt.Dimension(550, 600));
        getContentPane().add(background);
        background.setBounds(0, 0, 550, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class DroneThread extends Thread {
        @Override
        public void run()
        {
            while(true){
                credits+=drones;
                creditCount.setText("Credits: "+credits);
            }
        }
    }
    
    private void shopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopButtonActionPerformed
        //Go to the shop
        clicker.setVisible(false);
        shopButton.setVisible(false);
        alien_pic.setVisible(false);
        shopPanel.setVisible(true);
        shopPanel2.setVisible(true);
        clickerScreen.setVisible(true);
        prestige.setVisible(true);
        prestigeMessage.setVisible(true);
        upgradeCounters.setVisible(false);
    }//GEN-LAST:event_shopButtonActionPerformed

    private void clickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickerActionPerformed
        JLabel labelC = new JLabel(gain+"+");
        labelC.setForeground(Color.red);
        labelPlace.add(labelC);
        labelC.setVisible(true);
        labelC.setOpaque(true);
        Point mouseXY = new Point();
        PointerInfo xy = MouseInfo.getPointerInfo();
        mouseXY = xy.getLocation();
        mouseXY.translate(-10, -50);
        System.out.println(mouseXY);
        labelPlace.setLocation(mouseXY);
        //labelC.setSize(50, 50);
        credits += gain;
        creditCount.setText("Credits: "+credits);
        System.out.println(credits);
    }//GEN-LAST:event_clickerActionPerformed

    private void droneUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_droneUpgradeActionPerformed
        // Money over time upgrade
        if(credits >= 1000){
            credits-=1000;
            drones++;
            creditCount.setText("Credits: "+credits);
        }
    }//GEN-LAST:event_droneUpgradeActionPerformed

    private void clickerScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickerScreenActionPerformed
        // Go back to the main screen
        clicker.setVisible(true);
        shopButton.setVisible(true);
        alien_pic.setVisible(true);
        shopPanel.setVisible(false);
        shopPanel2.setVisible(false);
        clickerScreen.setVisible(false);
        prestige.setVisible(false);
        prestigeMessage.setVisible(false);
        upgradeCounters.setVisible(true);
        updateCounters();
    }//GEN-LAST:event_clickerScreenActionPerformed

    private void fuelUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelUpgradeActionPerformed
        // Level 1 uprade
        if(credits >= 50){
            credits-=50;
            gain+=2;
            fuel++;
            creditCount.setText("Credits: "+credits);
        }
    }//GEN-LAST:event_fuelUpgradeActionPerformed

    private void blasterUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blasterUpgradeActionPerformed
        // Level 2 upgrade
        if(credits >= 100){
            credits-=100;
            gain+=4;
            blasters++;
            creditCount.setText("Credits: "+credits);
        }
    }//GEN-LAST:event_blasterUpgradeActionPerformed

    private void suitUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suitUpgradeActionPerformed
        // Level 3 upgrade
        if(credits >= 500){
            credits-=500;
            gain+=20;
            suits++;
            creditCount.setText("Credits: "+credits);
        }
    }//GEN-LAST:event_suitUpgradeActionPerformed

    private void bombUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bombUpgradeActionPerformed
        // Level 4 upgrade
        if(credits >= 5000){
            credits-=5000;
            gain+=200;
            nukes++;
            creditCount.setText("Credits: "+credits);
        }
    }//GEN-LAST:event_bombUpgradeActionPerformed

    private void prestigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestigeActionPerformed
        // Prestige system
        if(credits >= prestigeCost){
            credits=0;
            gain=1;
            gain+=prestigeCount;
            prestigeCount++;
            blasters=0;
            fuel=0;
            suits=0;
            nukes=0;
            drones=0;
            updateCounters();
            creditCount.setText("Credits: "+credits);
            prestigeCountLabel.setVisible(true);
            prestigeCountLabel.setText("Prestige Count= "+prestigeCount);
        }
    }//GEN-LAST:event_prestigeActionPerformed

    void updateCounters(){
        fuelCount.setText("Fuel: "+fuel);
        blasterCount.setText("Blasters: "+blasters);
        suitCount.setText("Suits: "+suits);
        nukeCount.setText("Nukes: "+nukes);
        droneCount.setText("Drones: "+drones);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alienClicker2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alienClicker2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alienClicker2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alienClicker2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alienClicker2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alien_pic;
    private javax.swing.JLabel background;
    private javax.swing.JLabel blasterCostLabel;
    private javax.swing.JLabel blasterCount;
    private javax.swing.JButton blasterUpgrade;
    private javax.swing.JLabel bombCostLabel;
    private javax.swing.JButton bombUpgrade;
    private javax.swing.JButton clicker;
    private javax.swing.JButton clickerScreen;
    private javax.swing.JLabel creditCount;
    private javax.swing.JLabel droneCostLabel;
    private javax.swing.JLabel droneCount;
    private javax.swing.JButton droneUpgrade;
    private javax.swing.JLabel fuelCostLabel;
    private javax.swing.JLabel fuelCount;
    private javax.swing.JButton fuelUpgrade;
    private javax.swing.JPanel labelPlace;
    private javax.swing.JLabel nukeCount;
    private javax.swing.JButton prestige;
    private javax.swing.JLabel prestigeCountLabel;
    private javax.swing.JLabel prestigeMessage;
    private javax.swing.JButton shopButton;
    private javax.swing.JPanel shopPanel;
    private javax.swing.JPanel shopPanel2;
    private javax.swing.JLabel suitCostLabel;
    private javax.swing.JLabel suitCount;
    private javax.swing.JButton suitUpgrade;
    private javax.swing.JLabel title;
    private javax.swing.JPanel upgradeCounters;
    // End of variables declaration//GEN-END:variables
}
